version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: food-ordering-db
    environment:
      POSTGRES_DB: food_ordering
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Create additional user and database via init script
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=trust"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - food-ordering-network

volumes:
  postgres_data:

networks:
  food-ordering-network:
    driver: bridge
