# AlertManager Configuration for Food Ordering System

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@foodordering.local'
  smtp_auth_username: 'alerts@foodordering.local'
  smtp_auth_password: 'your-email-password'

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
  - match:
      severity: critical
    receiver: 'critical-receiver'
    repeat_interval: 5m
  - match:
      severity: warning
    receiver: 'warning-receiver'
    repeat_interval: 15m

receivers:
- name: 'default-receiver'
  email_configs:
  - to: 'admin@foodordering.local'
    subject: 'Food Ordering Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      {{ end }}

- name: 'critical-receiver'
  email_configs:
  - to: 'admin@foodordering.local,ops@foodordering.local'
    subject: 'CRITICAL: Food Ordering Alert'
    body: |
      CRITICAL ALERT!
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      {{ end }}
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#alerts'
    title: 'Critical Alert - Food Ordering System'
    text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

- name: 'warning-receiver'
  email_configs:
  - to: 'admin@foodordering.local'
    subject: 'Warning: Food Ordering Alert'
    body: |
      Warning Alert
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      {{ end }}

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'instance']
